services:
  app:
    container_name: hyeonworld_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "17002:17002"
    volumes:
      - .:/app
  environment:
    - NODE_ENV=development