name: trigger local development goCD job
on: [push]
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: TriggerLocalDevGoCDJob
        run: curl -X POST ${{ secrets.LOCAL_DEV_URL }}/go/api/webhooks/github/notify
